Registrar - new form item
CESNET/perun-wui pull request #149
Opened 2021-04-22 14:52 UTC by Vojtech-Sassmann

* Added support for the new form item EMBEDDED_GROUP_APPLICATION
which can be used for automatic group applications.
* When submitting application, user can now select groups to join, after
his vo application has been submitted.
* On submitted application detail, we show only the groups, which user
had selected.

2021-04-22 14:53 UTC, Vojtech-Sassmann commented
Has to be tested with changes: https://github.com/CESNET/perun/pull/3176

2021-04-26 07:57 UTC, balcirakpeter requested changes

2021-04-26 07:57 UTC, balcirakpeter commented on perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java
> +import cz.metacentrum.perun.wui.registrar.widgets.items.GroupCheckBox;
It seems that this import is not used.

2021-04-26 13:18 UTC, balcirakpeter approved these changes

2021-04-26 13:19 UTC, merged