Updates for BBMRI inputs
CESNET/perun-wui pull request #159
Opened 2021-05-25 05:26 UTC by dBucik

- expect base64 url safe rather than regular base64 for prefilling the
  value
- new methods for encoding/decoding base64urlSafe
- removed confusing call of encoding as base64 in zipString

2021-05-25 05:27 UTC, dBucik commented
Also fixes:
https://github.com/CESNET/perun-wui/issues/158

2021-05-25 10:20 UTC, zlamalp requested changes

2021-05-25 10:20 UTC, zlamalp commented on perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/JsUtils.java
> +		return decodeBase64(base64UrlSafeToNonSafe(encodedString));
You can't reference other native methods in GWT directly. See: http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJSNI.html
or simply create standard java method as a wrapper, which will perform passing results of first call to the second and returning results.

2021-05-25 10:20 UTC, zlamalp commented on perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/JsUtils.java
> +		return base64ToUrlSafe(encodeBase64(decodedString));
Same here.

2021-05-26 13:33 UTC, zlamalp approved these changes

2021-05-26 13:33 UTC, merged